[package]
name = "libncmdump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "libncmdump"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.79"
ncmdump = "0.6.1"
pyo3 = "0.19.0"
